#ifndef ASSETSADDRESSES_H
#define ASSETSADDRESSES_H

#define ROOT_FOLDER "../assets"
#define BG_IMG_ADDR ROOT_FOLDER "/background_image.png"
#define REGULAR_BLOCK_ADDR ROOT_FOLDER "/sprites/objects/bricks_blocks/block.png"
#define GROUND_BLOCK_ADDR ROOT_FOLDER "/sprites/objects/bricks_blocks/ground_block.png"
#define MARIO_ADDR ROOT_FOLDER "/sprites/mario"
#define REGULAR_BRICK_ADDR ROOT_FOLDER "/sprites/objects/bricks_blocks/brick.png"
#define QUESTION_BRICK_ADDR ROOT_FOLDER "/sprites/objects/bricks_blocks/"
#define COIN_ADDR ROOT_FOLDER "/sprites/objects/coin.png"
#define LITTLE_GOOMBA_ADDR ROOT_FOLDER "/sprites/enemies/little_goomba/"
#define KOOPA_TROOPA_ADDR ROOT_FOLDER "/sprites/enemies/koopa_troopa/"
#define RED_MUSHROOM_ADDR ROOT_FOLDER "/sprites/objects/mushroom/red.png"
#define HEALTH_MUSHROOM_ADDR ROOT_FOLDER "/sprites/objects/mushroom/health.png"
#define PIPE_ADDR ROOT_FOLDER "/sprites/objects/pipe/"
#define FLAG_ADDR ROOT_FOLDER "/sprites/objects/flag/"
#define BACKGROUND_MUSIC ROOT_FOLDER "/sounds/background_music.mp3"
#define HEALTH_MUSHROOM_SOUND ROOT_FOLDER "/sounds/sound_effects/health-mushroom.wav"
#define ENEMY_STOMP_SOUND ROOT_FOLDER "/sounds/sound_effects/enemy-stomp.wav"
#define COIN_SOUND ROOT_FOLDER "/sounds/sound_effects/coin.wav"
#define BRICK_SMASH_SOUND ROOT_FOLDER "/sounds/sound_effects/brick-smash.wav"
#define GAMEOVER_SOUND ROOT_FOLDER "/sounds/sound_effects/gameover.wav"
#define JUMP_SMALL_SOUND ROOT_FOLDER "/sounds/sound_effects/jump-small.wav"
#define JUMP_SUPER_SOUND ROOT_FOLDER "/sounds/sound_effects/jump-super.wav"
#define LEVEL_CLEAR_SOUND ROOT_FOLDER "/sounds/sound_effects/level-clear.wav"
#define MARIOS_DEATH_SOUND ROOT_FOLDER "/sounds/sound_effects/mario-death.wav"
#define RED_MUSHROOM_SOUND ROOT_FOLDER "/sounds/sound_effects/powerup.wav"
#define RED_MUSHROOM_APPEARS_SOUND ROOT_FOLDER "/sounds/sound_effects/powerup-appears.wav"

#endif